-- Show all orders
SELECT * FROM orders;

-- Show customer name and product
SELECT customer_name,product FROM orders;

-- Show order id, product and status
SELECT order_id,product,status FROM orders;

-- Rename columns using aliases
SELECT customer_name AS customer,product AS item FROM orders;

-- Show product quantity and price
SELECT product,quantity,price FROM orders;

-- Show order id and customer name
SELECT order_id, customer_name FROM orders;




--     ___Filter rows with WHERE____

-- Completed orders
SELECT * FROM orders WHERE status = 'completed';
-- Explanation:
-- This query filters the orders table and shows only orders that are completed.
-- It helps us see which customer purchases have been successfully finished.

-- Pending orders
SELECT * FROM orders WHERE status = 'pending';

-- Cancelled orders
SELECT * FROM orders WHERE status = 'cancelled';

-- Price greater than 100
SELECT * FROM orders WHERE price > 100;

-- Price less than 100
SELECT * FROM orders WHERE price < 100;

-- Price greater or equal than 180
SELECT * FROM orders WHERE price >= 180;

-- Orders not cancelled
SELECT * FROM orders WHERE status != 'cancelled';

-- Orders from Arta
SELECT * FROM orders WHERE customer_name = 'Arta';

-- Mouse products
SELECT * FROM orders WHERE product = 'Mouse';




--   ___Combine filters with AND / OR____

-- Completed orders above 50
SELECT * FROM orders WHERE status = 'completed' AND price > 50;
-- Explanation:
-- This query combines two conditions using AND.
-- It returns only completed orders that have a price higher than 50.
-- It helps identify higher-value completed purchases.

-- Completed mouse orders
SELECT * FROM orders WHERE status = 'completed' AND product = 'Mouse';

-- Pending or Cancelled orders
SELECT * FROM orders WHERE status = 'pending' OR status = 'cancelled';

-- Dren completed orders
SELECT * FROM orders WHERE customer_name = 'Dren' and status = 'completed';

-- Laptop with price 700
SELECT * FROM orders WHERE product='Laptop' AND price=700;

-- Completed or expensive orders
SELECT * FROM orders WHERE status='completed' OR price > 500;

-- Not cancelled and price above 100
SELECT * FROM orders WHERE status!='cancelled' AND price > 100;




--   ___Sort and limit results____

-- Cheapest to expensive
SELECT * FROM orders ORDER BY price ASC;

-- Expensive to cheap
SELECT * FROM orders ORDER BY price DESC;

-- Top 3 expensive orders
SELECT * FROM orders ORDER BY price DESC LIMIT 3;
-- Explanation:
-- This query sorts orders from the highest price to the lowest price.
-- LIMIT 3 shows only the three most expensive orders.
-- It can be used to find the biggest customer purchases.

-- Cheapest 2 orders
SELECT * FROM orders ORDER BY price ASC LIMIT 2;

-- Completed highest price first
SELECT * FROM orders WHERE status='completed' ORDER BY price DESC;

-- Products alphabetically
SELECT product FROM orders ORDER BY product ASC;

-- Customers alphabetically
SELECT customer_name FROM orders ORDER BY customer_name ASC;




--   ___Calculated columns____

-- Create total amount
SELECT customer_name,product,quantity,price,quantity * price AS total_amount FROM orders;
-- Explanation:
-- This query creates a calculated column called total_amount.
-- It multiplies quantity by price to calculate the total value of each order.
-- This gives a clearer view of the revenue generated by each order.

-- Completed orders with total
SELECT customer_name,product,quantity * price AS total_amount FROM orders WHERE status='completed';

-- Completed orders sorted by total
SELECT customer_name,product,quantity * price AS total_amount FROM orders WHERE status='completed' ORDER BY total_amount DESC;
-- Explanation:
-- This query shows only completed orders and calculates their total amount.
-- The results are sorted from the highest total value to the lowest.
-- It helps businesses understand their completed revenue.

-- Cancelled or pending with total
SELECT customer_name, product,quantity * price AS total_amount FROM orders WHERE status='cancelled' OR status='pending';

-- Rename columns and calculate
SELECT customer_name AS customer,product AS item,quantity * price AS total_amount FROM orders;

-- Top 3 orders by total
SELECT *,quantity * price AS total_amount FROM orders ORDER BY total_amount DESC LIMIT 3;

-- Orders where total is greater than 100
SELECT *,quantity * price AS total_amount FROM orders WHERE quantity * price > 100;