DROP TABLE IF EXISTS clean_orders;

CREATE TABLE clean_orders (
    order_id INTEGER,
    customer_name TEXT,
    city TEXT,
    segment TEXT,
    product_name TEXT,
    category TEXT,
    quantity INTEGER,
    price REAL,
    status TEXT,
    channel TEXT,
    total_amount REAL
);


-- Insert clean Silver data generated by Python pipeline
INSERT INTO clean_orders VALUES
(1, 'Arta', 'Vushtrri', 'Individual', 'Laptop', 'Electronics', 1, 700, 'completed', 'online', 700),
(2, 'Blend', 'Prishtina', 'Individual', 'Mouse', 'Accessories', 2, 15, 'completed', 'store', 30),
(4, 'Elira', 'Vushtrri', 'Individual', 'Monitor', 'Electronics', 1, 180, 'cancelled', 'store', 180),
(5, 'Arta', 'Vushtrri', 'Individual', 'Mouse', 'Accessories', 3, 15, 'completed', 'online', 45),
(10, 'Jon', 'Prishtina', 'Business', 'Headphones', 'Accessories', 4, 50, 'pending', 'store', 200),
(11, 'Era', 'Vushtrri', 'Individual', 'Laptop', 'Electronics', 1, 700, 'completed', 'online', 700),
(12, 'Noar', 'Gjilan', 'Individual', 'Webcam', 'Electronics', 2, 90, 'completed', 'bank', 180),
(13, 'Sara', 'Peja', 'Business', 'Notebook', 'Office', 1, 5, 'cancelled', 'online', 5),
(15, 'Elira', 'Vushtrri', 'Individual', 'Monitor', 'Electronics', 5, 180, 'completed', 'store', 900),
(16, 'Valon', 'Gjilan', 'Individual', 'Mouse', 'Accessories', 2, 15, 'completed', 'online', 30),
(18, 'Leart', 'Peja', 'Business', 'Desk', 'Office', 1, 220, 'completed', 'unknown', 220),
(19, 'Faton', 'Prizren', 'Individual', 'Chair', 'Office', 3, 120, 'pending', 'web', 360),
(20, 'Gresa', 'Prishtina', 'Business', 'USB Cable', 'Accessories', 2, 8, 'completed', 'online', 16),
(21, 'Nora', 'Ferizaj', 'Individual', 'Headphones', 'Accessories', 1, 50, 'completed', 'store', 50),
(23, 'Era', 'Vushtrri', 'Individual', 'Notebook', 'Office', 2, 5, 'completed', 'online', 10),
(24, 'Noar', 'Gjilan', 'Individual', 'Laptop', 'Electronics', 1, 700, 'completed', 'store', 700);


-- Verify loaded data
SELECT * FROM clean_orders;